-- NOT EFFECTIVE YET.
INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2030-01-01 00:00:00.000'}, null, 1, 'config.string', 'NAM string value', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');
INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES (null, '*', '*', '*', '*', '*', {ts '2018-01-01 00:00:00.000'}, null, 1, 'config.string', 'ALL string value', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');

INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES (null, '*', '*', '*', '*', '*', {ts '2018-01-01 00:00:00.000'}, null, 1, 'config.int', '2000', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');
INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES ('REGION', 'NAM', 'US', 'OH', '101', '101-2', {ts '2030-01-01 00:00:00.000'}, null, 1, 'config.int', '1000', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');
INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES ('REGION', 'NAM', 'US', 'OH', '101', '101-1', {ts '2018-01-01 00:00:00.000'}, null, 1, 'config.int', '500', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');

INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES (null, '*', '*', '*', '*', '*', {ts '2018-01-01 00:00:00.000'}, null, 1, 'config.enabled.test', 'this one is ENABLED.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');
INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2018-01-01 00:00:00.000'}, null, 0, 'config.enabled.test', 'this one is disabled.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');

INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2030-01-01 00:00:00.000'}, null, 1, 'config.effective.test', 'this one is NOT EFFECTIVE YET.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');    
INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2010-01-01 00:00:00.000'}, {ts '2011-01-01 00:00:00.000'}, 1, 'config.effective.test', 'this one has expired.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');        
INSERT INTO CFG_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
    VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2011-01-01 00:00:00.000'}, null, 1, 'config.effective.test', 'this one should be active.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');            

