package org.jumpmind.pos.core.screen;

public interface IconType {
    public static final String Barcode = "Barcode"; //barcode.svg
    public static final String Percent = "Percent"; //percent.svg
    public static final String Search = "Search"; //search
    public static final String Help = "Help"; //help
    public static final String Receipt = "Receipt"; //receipt
    public static final String NoReceipt = "NoReceipt"; //block
    public static final String Error = "Error"; //error
    public static final String Login = "Login"; //lock
    public static final String Logout = "Logout"; //input
    public static final String Home = "Home"; //home
    public static final String DayStart = "DayStart"; //brightness_5
    public static final String DayEnd = "DayEnd"; //brightness_3
    public static final String Sales = "Sales"; //local_offer
    public static final String Phone = "Phone"; //phone or call
    public static final String DefaultPrompt = "DefaultPrompt"; //question_answer
    public static final String Forward = "Forward"; //keyboard_arrow_right
    public static final String Back = "Back"; //keyboard_arrow_left
    public static final String Customer = "Customer"; //person
    public static final String BusinessCustomer = "BusinessCustomer"; //business
    public static final String Employee = "Employee"; //person
    public static final String Employees = "Employees"; //group
    public static final String AddEmployee = "AddEmployee"; //person_add
    public static final String AddCustomer = "AddCustomer"; //person_add
    public static final String Email = "Email"; //email
    public static final String LoyaltyProgram = "LoyaltyProgram"; //loyalty
    public static final String CustomerLink = "CustomerLink"; //link
    public static final String ExternalLink = "ExternalLink"; //language;
    public static final String Links = "Links"; //link
    public static final String WebOrder = "WebOrder"; //computer
    public static final String Delivery = "Delivery"; //local_shipping
    public static final String Pickup = "Pickup"; //schedule
    public static final String Journal = "Journal"; //book
    public static final String Training = "Training"; //school
    public static final String Clock = "Clock"; //watch_later
    public static final String Calendar = "Calendar"; //today
    public static final String CalendarError = "CalendarError"; //event_busy
    public static final String CalendarOk = "CalendarOk"; //event_available
    public static final String Completed = "Completed"; //check or done
    public static final String DollarSign = "DollarSign"; //attach_money
    public static final String Discount = "Discount"; //local_offer
    public static final String Check = "Check"; //money
    public static final String Cash = "Cash"; //local_atm
    public static final String Coin = "Coin"; //monetization_on
    public static final String CreditCard = "CreditCard"; //credit_card
    public static final String GiftCard = "GiftCard"; //card_giftcard
    public static final String StoreCard = "StoreCard"; //card_membership
    public static final String PurchaseOrder = "PurchaseOrder"; //account_balance_wallet
    public static final String Lease = "Lease"; // account_balance
    public static final String Tax = "Tax"; //account_balance
    public static final String Account = "Account"; //account_balance
    public static final String Store = "Store"; //store
    public static final String EmployeeEnter = "EmployeeEnter"; //keyboard
    public static final String CustomerEnter = "CustomerEnter"; //dialpad
    public static final String ItemList = "ItemList"; //list
    public static final String Print = "Print"; //print
    public static final String Add = "Add"; //add
    public static final String Remove = "Remove"; //remove
    public static final String Increment = "Increment"; //add
    public static final String Decrement = "Decrement"; //remove
    public static final String AddToCart = "AddToCart"; //add_shopping_cart
    public static final String SuspendAction = "SuspendAction"; //pause
    public static final String ResumeAction = "ResumeAction"; //play_arrow
    public static final String RetrieveAction = "RetrieveAction"; //replay
    public static final String CancelAction = "CancelAction"; //block
    public static final String BypassAction = "BypassAction"; //low_priority
    public static final String ViewAction = "ViewAction"; //pageview
    public static final String Return = "Return"; //undo
    public static final String Trash = "Trash"; //delete
    public static final String Close = "Close"; //close
    public static final String Till = "Till"; //local_mall
    public static final String Security = "Security"; //security
    public static final String Reports = "Reports"; //assessment
    public static final String HamburgerMenu = "HamburgerMenu"; //menu
    public static final String KebabMenu = "KebabMenu"; //more_vert
    public static final String OrderHistory = "OrderHistory";
            
}