package org.jumpmind.pos.core.screen;

public enum ScreenType {
    BasicItemSearch,
    Cart,
    ChooseOptions,
    Dialog,
    EmbeddedWebPage,
    Form,
    DynamicForm,
    Home,
    ItemList,
    Login,
    PaymentStatus,
    Prompt,
    PromptWithOptions,
    NoOp,
    Transaction,
    SellItemDetail,
    SignatureCapture,
    Table,
    SaleRetrieval,
    Tendering,
    TillCurrencyCount,
    TillSummary,
    TillOtherTenderCount,
    WarrantyCoverage,
    Options,
    Blank,
    Change
}
