export enum TransTypeEnum {
    Sale = 'SALE',
    SaleOrder = 'SALE_ORDER',
    Return = 'RETURN',
    Inquiry = 'INQUIRY',
    ReturnOrder = 'RETURN_ORDER',
    Void = 'VOID',
    NoSale = 'NO_SALE',
    OpenBusinessUnit = 'OPEN_BUSINESS_UNIT',
    CloseBusinessUnit = 'CLOSE_BUSINESS_UNIT',
    OpenDevice = 'OPEN_DEVICE',
    CloseDevice = 'CLOSE_DEVICE',
    OpenTill = 'OPEN_TILL',
    CloseTill = 'CLOSE_TILL',
    ReconcileTill = 'RECONCILE_TILL',
    SuspendTill = 'SUSPEND_TILL',
    OpenStoreBank = 'OPEN_STORE_BANK',
    CloseStoreBank = 'CLOSE_STORE_BANK',
    PayIn = 'PAY_IN',
    PayOut = 'PAY_OUT',
    CashUp = 'CASH_UP',
    CashDown = 'CASH_DOWN',
    TrainingStart = 'TRAINING_START',
    TrainingEnd = 'TRAINING_END'
}