
INSERT into CTX_DEVICE(DEVICE_ID, DEVICE_TYPE, DESCRIPTION, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('100-1', 'WORKSTATION', 'Store 100 Register 1', 
    'N_AMERICA', 'US', 'OH', '100', 'REGULAR', 'WORKSTATION', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');    

INSERT into CTX_DEVICE(DEVICE_ID, DEVICE_TYPE, DESCRIPTION, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('500-1', 'WORKSTATION', 'Store 500 Register 1', 
    'N_AMERICA', 'US', 'CA', '500', 'POPUP', 'WORKSTATION', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');        
INSERT into CTX_DEVICE(DEVICE_ID, DEVICE_TYPE, DESCRIPTION, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('500-2', 'WORKSTATION', 'Store 500 Register 2', 
    'N_AMERICA', 'US', 'CA', '500', 'POPUP', 'WORKSTATION', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');            

INSERT into CTX_DEVICE(DEVICE_ID, DEVICE_TYPE, DESCRIPTION, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('900-10', 'WORKSTATION', 'Store 900 Register 10', 
    'EAST_AFRICA', 'UG', '', '900', 'REGULAR', 'MOBILE_POS', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');        
    
INSERT into CTX_DEVICE(DEVICE_ID, DEVICE_TYPE, DESCRIPTION, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('00039-011', 'WORKSTATION', 'Store 00039 Register 11',
    'EAST_AFRICA', 'UG', '', '00039', 'REGULAR', 'WORKSTATION', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');        
    
INSERT into CTX_DEVICE(DEVICE_ID, DEVICE_TYPE, DESCRIPTION, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('05243-013', 'WORKSTATION', 'Store 00039 Register 11',
    'EAST_AFRICA', 'UG', '', '00039', 'REGULAR', 'WORKSTATION', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');            

TRUNCATE TABLE CTX_CONFIG;

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            'Welcome global!' 
        );

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            'N_AMERICA', '*', '*', '*', '*', '*', '*', '*',
            'Welcome North America!' 
        );        
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            'N_AMERICA', 'US', '*', '*', '*', '*', '*', '*',
            'Welcome USA!' 
        );
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            'N_AMERICA', 'US', 'OH', '*', '*', '*', '*', '*',
            'Welcome OH, USA!' 
        );             
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            'N_AMERICA', 'US', 'OH', '100', '*', '*', '*', '*',
            'Welcome store 100 in OH, USA!' 
        );                     
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', 'OUTLET', '*', '*', '*',
            'Welcome outlet stores!' 
        );                             
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', 'MOBILE_POS', '*', '*',
            'Welcome mobile POS!' 
        );                          
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', 'METL', '*',
            'Welcome Metl brand!' 
        );                                     

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', 'POS',
            'Welcome POS app!' 
        );                                         
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            'EAST_AFRICA', 'UG', '*', '*', 'REGULAR', '*', 'Metl', 'POS',
            'Welcome UG POS app!' 
        );               
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.welcome.text', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            'EAST_AFRICA', 'UG', '*', '00039', 'REGULAR', 'WORKSTATION', 'Metl', 'POS',
            'Welcome super specific!' 
        );

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.login.timeout', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            'global login timeout' 
        );

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.login.retry.attempts', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            'N_AMERICA', 'US', 'OH', '*', '*', '*', '*', '*',
            '10' 
        );     

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('pos.login.retry.attempts', {ts '2000-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            'EAST_AFRICA', 'UG', '*', '*', '*', '*', '*', '*',
            '15' 
        );                

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.expired', {ts '2000-01-01 00:00:00.000'}, {ts '2010-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            'Value is expired.' 
        );                    

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.expired.one.active', {ts '2000-01-01 00:00:00.000'}, {ts '2010-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            'Value is expired.' 
        );                                        
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.expired.one.active', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            'Value is active.' 
        );                                

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.effective', {ts '2020-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            'Value is not effective yet' 
        );     
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.one.effective', {ts '2020-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            'Value is not effective yet' 
        );            
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.one.effective', {ts '2010-01-01 00:00:00.000'}, {ts '2020-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            'this one is effective' 
        );                        

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.integer', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '500' 
        );        
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.integer.bad', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '500b' 
        );        

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.long', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '50000000000' 
        );        
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.long.bad', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '50000000000b' 
        );              

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.date', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '2018-06-01' 
        );        
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.date.bad', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '2018-06-01bad' 
        );        

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.date.time.seconds', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '2018-06-01 16:25:32' 
        );                        

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.date.time.ms', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '2018-06-01 16:25:32.298' 
        );                                

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.simple.json', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '{
                "id":"1234",
                "sequence" : 888999,
                "createDate" : "2018-06-01T17:45:40.000"
            }' 
        );                                    

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.array.json', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '[{
                "id":"1234",
                "sequence" : 888999,
                "createDate" : "2018-06-01T17:45:40.000"
            },
            {
                "id":"56789",
                "sequence" : 888000,
                "createDate" : "2017-06-01T17:45:40.000"
            }
            ]' 
        );                                                

INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('test.decimal.json', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '{
                "id":"1234",
                "amount" : 34.45
            }' 
        );                                                


INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('openpos.user.warn.password.expires.days', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '5');      
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('openpos.user.max.login.attempts', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '10');             
INSERT INTO CTX_CONFIG(CONFIG_NAME, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_NUMBER, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE,
    CONFIG_VALUE)
    VALUES ('openpos.user.attempts.reset.period.ms', {ts '2010-01-01 00:00:00.000'}, {ts '2030-01-01 00:00:00.000'}, 1, CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test',
            '*', '*', '*', '*', '*', '*', '*', '*',
            '14400000');                              