
INSERT into CTX_NODE(NODE_ID, NODE_TYPE, DESCRIPTION, ADDRESS1, CITY, NODE_STATE, POSTAL_CODE, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('100', 'STORE_SERVER', 'Store 100', '4100 Regent St', 'Columbus', 'OH', '43219',
    'N_AMERICA', 'US', 'OH', 'REGULAR', 'SERVER', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');

INSERT into CTX_NODE(NODE_ID, NODE_TYPE, DESCRIPTION, ADDRESS1, CITY, NODE_STATE, POSTAL_CODE, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('100-1', 'WORKSTATION', 'Store 100 Register 1', '4100 Regent St', 'Columbus', 'OH', '43219',
    'N_AMERICA', 'US', 'OH', 'REGULAR', 'WORKSTATION', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');    

INSERT into CTX_NODE(NODE_ID, NODE_TYPE, DESCRIPTION, ADDRESS1, CITY, NODE_STATE, POSTAL_CODE, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('500-1', 'WORKSTATION', 'Store 500 Register 1', '1600 Amphitheatre Parkway', 'Mountain View', 'CA', '94043',
    'N_AMERICA', 'US', 'CA', 'POPUP', 'WORKSTATION', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');        
INSERT into CTX_NODE(NODE_ID, NODE_TYPE, DESCRIPTION, ADDRESS1, CITY, NODE_STATE, POSTAL_CODE, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('500-2', 'WORKSTATION', 'Store 500 Register 2', '1600 Amphitheatre Parkway', 'Mountain View', 'CA', '94043',
    'N_AMERICA', 'US', 'CA', 'POPUP', 'WORKSTATION', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');            

INSERT into CTX_NODE(NODE_ID, NODE_TYPE, DESCRIPTION, ADDRESS1, CITY, NODE_STATE, POSTAL_CODE, 
    TAG_REGION, TAG_COUNTRY, TAG_STATE, TAG_STORE_TYPE, TAG_DEVICE_TYPE, TAG_BRAND_ID, TAG_APP_PROFILE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
VALUES ('900-10', 'WORKSTATION', 'Store 900 Register 10', 'Plot 1577 Ggaba Road', 'Kampala', null, '94043',
    'EAST_AFRICA', 'UG', null, 'REGULAR', 'MOBILE', 'Metl', 'POS', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');        


TRUNCATE TABLE CTX_CONFIG;

-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2030-01-01 00:00:00.000'}, null, 1, 'config.string', 'NAM string value', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');
-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES (null, '*', '*', '*', '*', '*', {ts '2018-01-01 00:00:00.000'}, null, 1, 'config.string', 'ALL string value', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');

-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES (null, '*', '*', '*', '*', '*', {ts '2018-01-01 00:00:00.000'}, null, 1, 'config.int', '2000', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');
-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES ('REGION', 'NAM', 'US', 'OH', '101', '101-2', {ts '2030-01-01 00:00:00.000'}, null, 1, 'config.int', '1000', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');
-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES ('REGION', 'NAM', 'US', 'OH', '101', '101-1', {ts '2018-01-01 00:00:00.000'}, null, 1, 'config.int', '500', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');

-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES (null, '*', '*', '*', '*', '*', {ts '2018-01-01 00:00:00.000'}, null, 1, 'config.enabled.test', 'this one is ENABLED.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');
-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2018-01-01 00:00:00.000'}, null, 0, 'config.enabled.test', 'this one is disabled.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');

-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2030-01-01 00:00:00.000'}, null, 1, 'config.effective.test', 'this one is NOT EFFECTIVE YET.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');    
-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2010-01-01 00:00:00.000'}, {ts '2011-01-01 00:00:00.000'}, 1, 'config.effective.test', 'this one has expired.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');        
-- INSERT INTO CTX_CONFIG(LOCATION_TYPE, LOCATION_VALUE, STORE_TYPE, DEPARTMENT_ID, BRAND_ID, DEVICE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE, ENABLED_FLAG, CONFIG_NAME, CONFIG_VALUE, CREATE_TIME, CREATE_BY, LAST_UPDATE_TIME, LAST_UPDATE_BY)
--     VALUES ('REGION', 'NAM', '*', '*', '*', '*', {ts '2011-01-01 00:00:00.000'}, null, 1, 'config.effective.test', 'this one should be active.', CURRENT_TIMESTAMP, 'test', CURRENT_TIMESTAMP, 'test');            

