package org.jumpmind.pos.core.ui.message;

public final class UIMessageType {
    public static String SALE = "Sale";
    public static String SELECTION_LIST = "SelectionList";
    public static String RETURN = "Return";
    public static String DIALOG = "Dialog";
    public static String PROMPT = "Prompt";
    public static String PROMPT_WITH_OPTIONS = "PromptWithOptions";
    public static String PROMPT_WITH_INFO = "PromptWithInfo";
    public static String HOME = "Home";
    public static String CHOOSE_OPTIONS = "ChooseOptions";
    public static String OPTIONS = "Options";
    public static String SELF_CHECKOUT_HOME = "SelfCheckoutHome";
    public static String SELF_CHECKOUT_SALE = "SelfCheckoutSale";
    public static String SELF_CHECKOUT_FORM = "SelfCheckoutForm";
    public static String SELF_CHECKOUT_PROMPT = "SelfCheckoutPrompt";
    public static String SELF_CHECKOUT_TENDER = "SelfCheckoutTender";
    public static String SELF_CHECKOUT_OPTIONS = "SelfCheckoutOptions";
    public static String SIGNATURE_CAPTURE = "SignatureCapture";
    public static String PRICE_CHECKER_ITEM_DETAIL = "PriceCheckerItemDetail";
    public static String PRICE_CHECKER_HOME = "PriceCheckerHome";
    public static String LOADING_DIALOG = "LoadingDialog";
    public static String DYNAMIC_FORM = "DynamicForm";
    public static String ITEM_DETAIL = "ItemDetail";
    public static String TENDER = "Tender";
    public static String NO_OP = "NoOp";
    public static String AUTO_COMPLETE_ADDRESS = "AutoCompleteAddress";
    public static String CONFIRM_DIALOG = "ConfirmDialog";
    public static String DATA_TABLE = "DataTable";
    public static String SCAN_INPUT_DIALOG = "ScanInputDialog";
    public static String CUSTOMER_DISPLAY_HOME = "CustomerDisplayHome";
    public static String CUSTOMER_DISPLAY_SALE = "CustomerDisplaySale";
    public static String TRANSACTION_SEARCH = "TransactionSearch";
    public static String TRANSACTION_DETAILS = "TransactionDetails";
    public static String PROMOTION_SEARCH = "PromotionSearch";
    public static String SIMULATED_PERIPHERAL = "SimulatedPeripheral";
    public static String AUDIO = "Audio";
    public static String AUDIO_CONFIG = "AudioConfig";
    public static String AUDIO_PRELOAD = "AudioPreload";
}
