package org.jumpmind.pos.service.startup;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Properties;

import javax.annotation.PostConstruct;

import org.apache.commons.lang.StringUtils;
import org.jumpmind.pos.service.IModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class ModuleRegistry {

    final Logger logger = LoggerFactory.getLogger(getClass());

    @Autowired(required = false)
    List<IModule> modules;

    public ModuleRegistry() {
        logger.info("Creating module registry");
    }

    @PostConstruct
    public void loadModuleDatabaseDefaults() {
        if (this.modules != null) {
            File file = new File("work", ".h2.server.properties");
            Properties properties = new Properties();
            try {
                if (file.exists()) {
                    try (InputStream is = new FileInputStream(file)) {
                        properties.load(is);
                    }
                }
                if (!properties.containsKey("commandHistory")) {
                    properties.setProperty("commandHistory", "");
                }
                properties.setProperty("webAllowOthers", "false");
                int pos = 0;
                for (IModule module : modules) {
                    properties.setProperty(Integer.toString(pos), StringUtils.capitalize(module.getName()) + "|" + module.getDriver() + "|"
                            + module.getURL().replace("jdbc:openpos:", "jdbc:") + "|\n");
                    pos++;
                }
                try (BufferedWriter out = new BufferedWriter(new FileWriter(file))) {
                    properties.store(out, "generated by nu commerce");
                }
            } catch (IOException e) {
                logger.warn("Unable to configure \".h2.server.properties\" file");
            }
        }

    }

    public List<IModule> getModules() {
        return modules;
    }

}
