export const Configuration = {
    mimicScroll: false,
    useOnScreenKeyboard: false,
    useTouchListener: true,
    useSavePoints: true,
    showRegisterStatus: false,
    clickableRegisterStatus: false,
    offlineOnlyRegisterStatus: false,
    keepAliveMillis: 30000,
    compatibilityVersion: 'v1',
    incompatibleVersionMessage: 'Application is not compatible with the server.',
    maxSignaturePoints: -1,
    maxResponseSizeBytes: 79500,
    enableAutocomplete: false,
    enableMenuClose: true,
};
